lenguage: python
python:
  - "3.8"

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install pytest
  - pip install --user -r requirements.txt

script:
  - python -m pytest tests/
